import type {
	FreeSpinConfig,
	GameMathConfig,
	PaytableEntry,
	ReelStrip,
	SymbolDefinition,
} from './types';

const symbolDefinitions: ReadonlyArray<SymbolDefinition> = [
	{
		id: 'low_ten',
		displayName: '10',
		tier: 'low',
		assetKey: 'symbol_low_ten',
		description: 'Neon ten glyph',
	},
	{
		id: 'low_jack',
		displayName: 'J',
		tier: 'low',
		assetKey: 'symbol_low_jack',
		description: 'Neon jack glyph',
	},
	{
		id: 'low_queen',
		displayName: 'Q',
		tier: 'low',
		assetKey: 'symbol_low_queen',
		description: 'Neon queen glyph',
	},
	{
		id: 'low_king',
		displayName: 'K',
		tier: 'low',
		assetKey: 'symbol_low_king',
		description: 'Neon king glyph',
	},
	{
		id: 'low_ace',
		displayName: 'A',
		tier: 'low',
		assetKey: 'symbol_low_ace',
		description: 'Neon ace glyph',
	},
	{
		id: 'mid_cache',
		displayName: 'Cache Stack',
		tier: 'mid',
		assetKey: 'symbol_mid_cache',
		description: 'Layered crypto cache cube',
	},
	{
		id: 'mid_vaultkey',
		displayName: 'Vault Key',
		tier: 'mid',
		assetKey: 'symbol_mid_vaultkey',
		description: 'Chromed vault keycard',
	},
	{
		id: 'mid_chip',
		displayName: 'Plasma Chip',
		tier: 'mid',
		assetKey: 'symbol_mid_chip',
		description: 'Glowing chip coin',
	},
	{
		id: 'premium_pilot',
		displayName: 'Meta Pilot',
		tier: 'premium',
		assetKey: 'symbol_premium_pilot',
		description: 'Avatar guardian of the vault',
	},
	{
		id: 'premium_ai',
		displayName: 'Vault AI',
		tier: 'premium',
		assetKey: 'symbol_premium_ai',
		description: 'Diamond token intelligence core',
	},
	{
		id: 'premium_token',
		displayName: 'Diamond Token',
		tier: 'premium',
		assetKey: 'symbol_premium_token',
		description: 'Premium diamond reward token',
	},
	{
		id: 'wild_vault',
		displayName: 'Vault Wild',
		tier: 'wild',
		assetKey: 'symbol_wild',
		description: 'Expanding neon wild multiplier',
	},
	{
		id: 'scatter_vault',
		displayName: 'Meta Vault Scatter',
		tier: 'scatter',
		assetKey: 'symbol_scatter',
		description: 'Trigger for free spins',
	},
	{
		id: 'collect_gold_chip',
		displayName: 'Gold Chip',
		tier: 'collectible',
		assetKey: 'symbol_collect_gold_chip',
		description: 'Collectible upgrade chip',
	},
];

const paytable: ReadonlyArray<PaytableEntry> = [
	{
		symbol: 'low_ten',
		payouts: { 3: 0.1, 4: 0.2, 5: 0.5 },
	},
	{
		symbol: 'low_jack',
		payouts: { 3: 0.1, 4: 0.2, 5: 0.5 },
	},
	{
		symbol: 'low_queen',
		payouts: { 3: 0.15, 4: 0.3, 5: 0.6 },
	},
	{
		symbol: 'low_king',
		payouts: { 3: 0.2, 4: 0.4, 5: 0.7 },
	},
	{
		symbol: 'low_ace',
		payouts: { 3: 0.2, 4: 0.4, 5: 0.7 },
	},
	{
		symbol: 'mid_cache',
		payouts: { 3: 0.3, 4: 0.6, 5: 1.5 },
	},
	{
		symbol: 'mid_vaultkey',
		payouts: { 3: 0.3, 4: 0.8, 5: 1.8 },
	},
	{
		symbol: 'mid_chip',
		payouts: { 3: 0.4, 4: 1.0, 5: 2.0 },
	},
	{
		symbol: 'premium_pilot',
		payouts: { 3: 0.6, 4: 1.5, 5: 3.0 },
	},
	{
		symbol: 'premium_ai',
		payouts: { 3: 0.8, 4: 2.0, 5: 4.0 },
	},
	{
		symbol: 'premium_token',
		payouts: { 3: 1.0, 4: 2.5, 5: 5.0 },
	},
	{
		symbol: 'scatter_vault',
		payouts: { 3: 2.0, 4: 10.0, 5: 50.0 },
	},
];

const reelStrips: ReadonlyArray<ReelStrip> = [
	{
		reelIndex: 0,
		symbols: [
			'low_ten',
			'low_ace',
			'mid_cache',
			'low_queen',
			'mid_vaultkey',
			'low_jack',
			'premium_pilot',
			'low_king',
			'mid_chip',
			'low_ten',
			'premium_ai',
			'collect_gold_chip',
			'low_ace',
			'scatter_vault',
			'low_queen',
		],
	},
	{
		reelIndex: 1,
		symbols: [
			'low_king',
			'low_ten',
			'mid_chip',
			'low_jack',
			'mid_vaultkey',
			'low_queen',
			'premium_ai',
			'low_ace',
			'collect_gold_chip',
			'mid_cache',
			'low_king',
			'premium_token',
			'low_jack',
			'scatter_vault',
			'low_queen',
		],
	},
	{
		reelIndex: 2,
		symbols: [
			'low_ace',
			'mid_cache',
			'low_ten',
			'premium_ai',
			'collect_gold_chip',
			'low_jack',
			'mid_chip',
			'low_queen',
			'premium_pilot',
			'low_king',
			'scatter_vault',
			'low_ten',
			'mid_vaultkey',
			'low_ace',
			'premium_token',
		],
	},
	{
		reelIndex: 3,
		symbols: [
			'low_queen',
			'mid_vaultkey',
			'low_jack',
			'premium_token',
			'low_ten',
			'mid_cache',
			'collect_gold_chip',
			'low_ace',
			'premium_ai',
			'low_king',
			'scatter_vault',
			'low_jack',
			'mid_chip',
			'low_queen',
			'premium_pilot',
		],
	},
	{
		reelIndex: 4,
		symbols: [
			'low_king',
			'mid_chip',
			'low_queen',
			'premium_pilot',
			'low_ace',
			'collect_gold_chip',
			'mid_cache',
			'low_ten',
			'premium_ai',
			'low_jack',
			'mid_vaultkey',
			'scatter_vault',
			'low_queen',
			'premium_token',
			'low_king',
		],
	},
];

const freeSpinConfig: FreeSpinConfig = {
	triggerSpins: {
		3: 8,
		4: 15,
		5: 20,
	},
	retriggerTwoScatterSpins: 5,
	retriggerMultiScatterSpins: 8,
	maxFreeSpins: 150,
	upgradeThresholds: [4, 7, 12, 15],
	wildMultiplierReels: [2, 3, 4],
	wildMultiplierValues: [2, 3],
	buyFeatureOptions: [
		{ spins: 8, costMultiplier: 100 },
		{ spins: 15, costMultiplier: 200 },
		{ spins: 20, costMultiplier: 400 },
	],
};

export const cryptoStacksMathConfig: GameMathConfig = {
	name: 'Crypto Stacks: Meta Vault',
	reels: 5,
	rows: 4,
	ways: 1024,
	volatility: 'high',
	baseStake: 1,
	symbols: symbolDefinitions,
	paytable,
	reelStrips,
	freeSpins: freeSpinConfig,
	rtpBands: [
		{ mode: 'default', rtp: 0.963 },
		{ mode: 'jurisdictional', jurisdiction: 'low', rtp: 0.96 },
	],
	scatterSymbol: 'scatter_vault',
	wildSymbol: 'wild_vault',
	collectibleSymbol: 'collect_gold_chip',
};
